#!/usr/bin/env node
// Render the same HTML/CSS as the first frame of the app into iOS startup images.
// Requires Playwright + Chromium. Optional runtime paths:
// PLAYWRIGHT_MODULE=/path/to/playwright/index.mjs CHROMIUM_EXECUTABLE=/path/to/chromium node scripts/launch-screens.mjs
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createServer } from 'node:http';
import { resolve, extname } from 'node:path';
import { pathToFileURL } from 'node:url';

const root = resolve(import.meta.dirname, '../server/public');
const htmlFile = resolve(root, 'index.html');
const html = await readFile(htmlFile, 'utf8');
const profiles = [
  [375, 667, 2], [414, 736, 3], [375, 812, 3], [390, 844, 3],
  [393, 852, 3], [414, 896, 2], [414, 896, 3], [428, 926, 3],
  [430, 932, 3], [402, 874, 3], [440, 956, 3], [420, 912, 3],
  [768, 1024, 2], [810, 1080, 2], [820, 1180, 2], [834, 1194, 2],
  [1024, 1366, 2], [744, 1133, 2], [834, 1112, 2], [1032, 1376, 2],
];
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE
  ? pathToFileURL(resolve(process.env.PLAYWRIGHT_MODULE)).href : 'playwright');
const server = createServer(async (req, res) => {
  const path = new URL(req.url, 'http://localhost').pathname;
  try {
    if (path === '/') {
      // Keep the initial frame: do not load the app or the full stylesheet.
      res.setHeader('Content-Type', 'text/html');
      res.end(html.replace(/<script[^>]*>[\s\S]*?<\/script>/g, '').replace(/<link rel="stylesheet"[^>]*>/g, ''));
    } else {
      const file = resolve(root, '.' + path);
      if (!file.startsWith(root + '/')) throw new Error('outside root');
      res.setHeader('Content-Type', extname(file) === '.png' ? 'image/png' : 'text/plain');
      res.end(await readFile(file));
    }
  } catch { res.writeHead(404); res.end(); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const origin = `http://127.0.0.1:${server.address().port}`;
await mkdir(resolve(root, 'launch'), { recursive: true });
const browser = await chromium.launch({ headless: true,
  ...(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE } : {}) });
const links = [];
try {
  for (const [width, height, scale] of profiles) {
    for (const orientation of ['portrait', 'landscape']) {
      for (const theme of ['light', 'dark']) {
        const viewport = orientation === 'portrait' ? { width, height } : { width: height, height: width };
        const context = await browser.newContext({ viewport, deviceScaleFactor: scale, colorScheme: theme });
        const page = await context.newPage();
        await page.goto(origin);
        await page.locator('.boot-splash img').evaluate(img => img.decode());
        const name = `${viewport.width * scale}x${viewport.height * scale}-${theme}.png`;
        await page.screenshot({ path: resolve(root, 'launch', name) });
        const media = `(device-width: ${width}px) and (device-height: ${height}px) and (-webkit-device-pixel-ratio: ${scale}) and (orientation: ${orientation}) and (prefers-color-scheme: ${theme})`;
        links.push(`    <link rel="apple-touch-startup-image" href="/launch/${name}" media="${media}" />`);
        await context.close();
      }
    }
  }
  const block = `    <!-- iOS launch images: generated by scripts/launch-screens.mjs -->\n${links.join('\n')}\n    <!-- /iOS launch images -->`;
  const previous = /    <!-- iOS launch images:[\s\S]*?    <!-- \/iOS launch images -->/;
  await writeFile(htmlFile, previous.test(html) ? html.replace(previous, block) : html.replace('    <style>', block + '\n    <style>'));
  console.log(`Rendered ${links.length} startup images from the initial app frame.`);
} finally {
  await browser.close();
  await new Promise(resolve => server.close(resolve));
}
